swagger: "2.0"
consumes:
- application/json
produces:
- application/json
info:
  title: User Microservice
  description: User microservice
  version: 1.0.0
schemes:
- http

paths:
  /users:
    get:
      tags:
        - users
      summary: Returns all users
      operationId: get_users
      responses:
        200:
          description: List all users
          schema:
            type: array
            items:
              $ref: "#/definitions/user"
        default:
          description: Generic error response
          schema:
            $ref: "#/definitions/error"
    
    post:
      tags:
        - users
      operationId: add_user
      parameters:
        - name: body
          in: body
          schema: 
            $ref: "#/definitions/user"
      responses:
        201:
          description: User created
          schema:
            $ref: "#/definitions/user"
        default:
          description: Generic error response
          schema:
            $ref: "#/definitions/error"

definitions:
  # User
  user:
    type: object
    required:
      - username
      - password
      - gamerTag
      - firstName
      - lastName
      - email
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      username:
        type: string
        minLength: 6
      password:
        type: string
        minLength: 6
      gamerTag: 
        type: string
        minLength: 2
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string

  #Generic error
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string